backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: proyectos
    label: Proyectos
    folder: content/proyectos
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Título, name: titulo, widget: string }
      - { label: Categoría, name: categoria, widget: select, options: ["Electricidad", "Domótica", "Redes y CCTV"] }
      - { label: Descripción, name: descripcion, widget: text }
      - { label: Imagen, name: imagen, widget: image }
      - { label: Ubicación, name: ubicacion, widget: string, required: false }

  - name: testimonios
    label: Testimonios
    folder: content/testimonios
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Nombre, name: nombre, widget: string }
      - { label: Empresa, name: empresa, widget: string, required: false }
      - { label: Testimonio, name: testimonio, widget: text }
      - { label: Estrellas, name: estrellas, widget: number, min: 1, max: 5, default: 5 }